
incident_types = [
    'Traumatic Injury',
    'Bleeding',
    'Respiratory distress',
    'Domestic Violence',
    'Behavioral/Psychiatric',
    'Theft',
    'Loss of consciousness / fainting',
    'Seizure',
    'Fight',
    'Property Fire',
    'Gunshot Wound',
    'Stabbing',
    'Overdose',
    'Cardiac arrest',
    'Vehicle accident'
]

content_types = [
    'Image',
    'Video',
    'Sound recording'
]

cities_states = {
    'Los Angeles': 'CA',
    'San Francisco': 'CA',
    'Birmingham': 'AL',
    'Anchorage': 'AK',
    'Phoenix': 'AZ',
    'Little Rock': 'AR',
    'Denver': 'CO',
    'Bridgeport': 'CT',
    'Wilmington': 'DE',
    'Jacksonville': 'FL',
    'Miami': 'FL',
    'Atlanta': 'GA',
    'Honolulu': 'HI',
    'Boise': 'ID',
    'Chicago': 'IL',
    'Indianapolis': 'IN',
    'Des Moines': 'IA',
    'Wichita': 'KS',
    'Louisville': 'KY',
    'New Orleans': 'LA',
    'Portland': 'ME',
    'Baltimore': 'MD',
    'Boston': 'MA',
    'Detroit': 'MI',
    'Minneapolis': 'MN',
    'Jackson': 'MS',
    'Kansas City': 'MO',
    'Billings': 'MT',
    'Omaha': 'NE',
    'Las Vegas': 'NV',
    'Manchester': 'NH',
    'Newark': 'NJ',
    'Albuquerque': 'NM',
    'New York City': 'NY',
    'Buffalo': 'NY',
    'Charlotte': 'NC',
    'Fargo': 'ND',
    'Columbus': 'OH',
    'Oklahoma City': 'OK',
    'Portland': 'OR',
    'Philadelphia': 'PA',
    'Providence': 'RI',
    'Charleston': 'SC',
    'Sioux Falls': 'SD',
    'Nashville': 'TE',
    'Houston': 'TX',
    'Austin': 'TX',
    'Salt Lake City': 'UT',
    'Burlington': 'VT',
    'Virginia Beach': 'VA',
    'Seattle': 'WA',
    'Charleston': 'WV',
    'Milwaukee': 'WI',
    'Cheyenne': 'WY'
}
